# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: hyprland-atomic
description: Minimal GNOME base with Hyprland on Fedora 43 base.

# Base Image: Bazzite GNOME
base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: stable

modules:
  # 1. DNF Module: Handles Repos, Installs, and Removals
  # This automatically detects you are on Fedora 43 and pulls matching repos.
  - type: dnf
    repos:
      copr:
        - solopasha/hyprland
        - pgdev/ghostty
    
    install:
      packages:
        # --- Hyprland Core ---
        - hyprland
        - hyprpaper
        - hypridle
        - hyprlock
        - xdg-desktop-portal-hyprland
        - waybar
        - wofi
        - mako
        - grimblast
        - copyq
        - pamixer
        - brightnessctl
        - wob
        - hyprpolkitagent  # Replaces polkit-gnome
        
        # --- Tools ---
        - ghostty
        - neovim
        - zsh
        # Removed 'tmux', 'fastfetch' (Conflict: Already in F43 base)
        
        # --- Media ---
        - mpv
        - yt-dlp
        # Removed 'gstreamer'/'libavcodec' (Conflict: Managed by Bazzite internally)

        # --- Sysadmin ---
        - htop
        - glances
        - screen
        # Removed 'wget', 'curl', 'bind-utils' (Conflict: Already in F43 base)

    remove:
      packages:
        # The Great Purge: Removing GNOME Apps
        - firefox
        - firefox-langpacks
        - gnome-calculator
        - gnome-calendar
        - gnome-characters
        - gnome-clocks
        - gnome-contacts
        - gnome-font-viewer
        - gnome-logs
        - gnome-maps
        - gnome-weather
        - gnome-disk-utility
        - gnome-system-monitor
        - gnome-text-editor
        - baobab
        - totem
        - loupe
        - snapshot
        - simple-scan
        - evince
        - yelp
        - gnome-tour
        - gnome-software

  # 2. Flatpaks
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - com.valvesoftware.Steam
          - com.discordapp.Discord
          - io.github.arunanshub.animdl
          - com.obsproject.Studio
          - org.gimp.GIMP
      - scope: user

  # 3. System Signing
  - type: signing
  
  # 4. Custom Scripts
  - type: script
    scripts:
      - build.sh
