# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: hyprland-atomic
description: Minimal GNOME base with Hyprland using the DNF module.

base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: stable

modules:
  # The DNF module handles Repos, Installs, and Removals in one block
  - type: dnf
    repos:
      copr:
        - solopasha/hyprland
        - pgdev/ghostty
    
    install:
      packages:
        # --- Hyprland Core ---
        - hyprland
        - hyprpaper
        - hypridle
        - hyprlock
        - xdg-desktop-portal-hyprland
        - waybar
        - wofi
        - mako
        - grimblast
        - copyq
        - pamixer
        - brightnessctl
        - wob
        - polkit-gnome

        # --- Tools ---
        - ghostty
        - neovim
        - zsh
        - tmux
        - fastfetch
        - yadm

        # --- Media ---
        - mpv
        - yt-dlp
        # REMOVED: gstreamer/libavcodec packages (Bazzite handles these internally)
        # Bazzite uses a pre-configured multimedia group, so adding them manually fails.

        # --- Sysadmin ---
        - htop
        - glances
        - screen
        # REMOVED: wget, curl, bind-utils (Already installed in the base image)

    remove:
      packages:
        - firefox
        - firefox-langpacks
        - gnome-calculator
        - gnome-calendar
        - gnome-characters
        - gnome-clocks
        - gnome-contacts
        - gnome-font-viewer
        - gnome-logs
        - gnome-maps
        - gnome-weather
        - gnome-disk-utility
        - gnome-system-monitor
        - gnome-text-editor
        - baobab
        - totem
        - loupe
        - snapshot
        - simple-scan
        - evince
        - yelp
        - gnome-tour
        - gnome-software

  # Flatpak configuration
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - com.valvesoftware.Steam
          - com.discordapp.Discord
          - io.github.arunanshub.animdl
          - com.obsproject.Studio
          - org.gimp.GIMP
      - scope: user

  - type: signing
  
  - type: script
    scripts:
      - build.sh
