general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = playerctl -a pause; pidof hyprlock || hyprlock
    after_sleep_cmd = hyprctl dispatch dpms on
    on_unlock_cmd = pkill -TERM -x hyprlock

    inhibit_sleep = 3
    ignore_dbus_inhibit = false
}

listener {
    timeout = 270
    on-timeout = brightnessctl -s set 10%
    on-resume = brightnessctl -r
}

listener {
    timeout = 300
    on-timeout = playerctl -a pause; pidof hyprlock || hyprlock
}

listener {
    timeout = 305
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 420
    on-timeout = sh -c '[ "$(cat /sys/class/power_supply/AC*/online)" -eq 0 ] && systemctl suspend'
}
