[default]
anchor = bottom center
margin = 50
width = 400
height = 25
border_size = 2
bar_padding = 4

# Catppuccin Mocha in wob's RRGGBBAA format.
background_color = 1e1e2edd
bar_color = 89b4faff
border_color = 313244ff
